services:
  - type: web
    name: library-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn library_api.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nome-do-seu-db
          property: connectionString
